import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const fiscalDocuments = sqliteTable("fiscal_documents", {
  id: text("id").primaryKey(),
  documentNumber: integer("document_number").notNull(),
  documentType: text("document_type").notNull(),
  issuedAt: text("issued_at").notNull(),
  closureDate: text("closure_date").notNull(),
  locationId: text("location_id").notNull(),
  tableId: text("table_id"),
  tableLabel: text("table_label"),
  paymentMethod: text("payment_method").notNull(),
  serviceType: text("service_type"),
  total: real("total").notNull(),
  changeAmount: real("change_amount"),
  operatorStaffId: text("operator_staff_id"),
  operatorName: text("operator_name"),
  shiftId: text("shift_id"),
  status: text("status").notNull().default("ISSUED"),
  voidedAt: text("voided_at"),
  voidedByStaffId: text("voided_by_staff_id"),
  voidReason: text("void_reason"),
  invoiceId: text("invoice_id"),
  invoiceNumber: text("invoice_number"),
  customerBusinessName: text("customer_business_name"),
  receiptJson: text("receipt_json").notNull(),
  metaJson: text("meta_json"),
  fileJsonPath: text("file_json_path"),
  fileTxtPath: text("file_txt_path"),
  createdAt: text("created_at").notNull(),
});
